# Import needed here for django models:
from . import authentication_model  # noqa
from . import authenticationmethods_model  # noqa
from . import conversionqueueitem_model  # noqa
from . import group_model  # noqa
from . import location_model  # noqa
from . import match_model  # noqa
from . import organization_model  # noqa
from . import referrerurl_model  # noqa
from . import rules  # noqa
from . import scannerjobs  # noqa
from . import scans  # noqa
from . import sensitivity_level  # noqa
from . import statistic_model  # noqa
from . import summary_model  # noqa
from . import urllastmodified_model  # noqa
from . import userprofile_model  # noqa
from . import version_model  # noqa
from . import webversion_model  # noqa
