# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-11 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0004_auto_20180524_1153'),
        ('os2webscanner', '0036_auto_20180619_1416'),
    ]

    operations = [
    ]
