# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0044_auto_20180907_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexrule',
            name='cpr_enabled',
            field=models.BooleanField(default=False, verbose_name='Scan CPR'),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='do_modulus11',
            field=models.BooleanField(default=False, verbose_name='Tjek modulus-11'),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='ignore_irrelevant',
            field=models.BooleanField(default=False, verbose_name='Ignorer ugyldige fødselsdatoer'),
        ),
    ]
