# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0062_scanner_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='authentication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os2webscanner_domain_authentication', to='os2webscanner.Authentication', verbose_name='Brugernavn'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os2webscanner_domain_groups', to='os2webscanner.Group', verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='os2webscanner_domain_organization', to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='regexrule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='os2webscanner.Group', verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='regexrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webscans', to='os2webscanner.Scanner', verbose_name='webscanner'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='os2webscanner.Group', verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='os2webscanner.Group', verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Bruger'),
        ),
    ]
