# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0065_urllastmodified_indices'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM os2webscanner_statistic WHERE scan_id IS NULL", migrations.RunSQL.noop, elidable=True),
        migrations.AlterField(
            model_name='statistic',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanjob', to='os2webscanner.Scan', verbose_name='scanjob'),
        ),
    ]
