# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-01 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0013_auto_20180501_1006'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scan',
            table='os2webscanner_scan',
        ),
    ]
