# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-01 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0016_filescan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filescan',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='filescan',
            name='scan_ptr',
        ),
        migrations.RemoveField(
            model_name='filescan',
            name='scanner',
        ),
        migrations.DeleteModel(
            name='FileScan',
        ),
    ]
