# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0027_auto_20180504_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Navn')),
                ('sensitivity', models.IntegerField(choices=[(0, 'Grøn'), (1, 'Gul'), (2, 'Rød')], default=2, verbose_name='Følsomhed')),
                ('regexrules', models.ManyToManyField(to='os2webscanner.RegexRule')),
            ],
        ),
        migrations.AddField(
            model_name='scanner',
            name='rules_sets',
            field=models.ManyToManyField(to='os2webscanner.RulesSet', verbose_name='Regler sæt'),
        ),
    ]
