# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0028_auto_20180528_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesset',
            name='description',
            field=models.TextField(default='', verbose_name='Beskrivelse'),
        ),
    ]
