# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0029_rulesset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesset',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
    ]
