# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0033_auto_20180613_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='files_added_to_the_queue_count',
            new_name='files_added_to_the_conversion_queue_count',
        ),
        migrations.AddField(
            model_name='statistic',
            name='files_is_dir_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='files_scraped_count',
            field=models.IntegerField(default=0),
        ),
    ]
