# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-14 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0034_auto_20180613_1136'),
        ('os2webscanner', '0030_auto_20180604_1515'),
    ]

    operations = [
    ]
