# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-14 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0038_auto_20180813_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regexrule',
            name='cpr_enabled',
        ),
        migrations.RemoveField(
            model_name='regexrule',
            name='ignore_irrelevant',
        ),
        migrations.RemoveField(
            model_name='regexrule',
            name='mod11_enabled',
        ),
    ]
