# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0039_auto_20180814_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexrule',
            name='cpr_enabled',
            field=models.BooleanField(default=False, verbose_name='Scan CPR'),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='ignore_irrelevant',
            field=models.BooleanField(default=False, verbose_name='Ignorer ugyldige fødselsdatoer'),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='mod11_enabled',
            field=models.BooleanField(default=False, verbose_name='Tjek modulus-11'),
        ),
    ]
