# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-18 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0045_auto_20180802_1248'),
    ]

    operations = [
    ]
