# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-19 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0047_merge_20180918_1341'),
        ('os2webscanner', '0045_auto_20180907_1509'),
    ]

    operations = [
    ]
