# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-19 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0048_merge_20180919_1106'),
        ('os2webscanner', '0046_auto_20180917_1328'),
    ]

    operations = [
    ]
