# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-09 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0050_auto_20181009_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangescanner',
            name='dir_to_scan',
        ),
        migrations.AddField(
            model_name='exchangedomain',
            name='dir_to_scan',
            field=models.CharField(max_length=2048, null=True, verbose_name='Exchange export sti'),
        ),
    ]
