# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0063_add_ondeletes_everywhere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='referrerurl',
            options={'verbose_name': 'Referer URL'},
        ),
        migrations.AlterModelOptions(
            name='regexpattern',
            options={'verbose_name': 'Pattern'},
        ),
        migrations.AlterModelOptions(
            name='scan',
            options={'verbose_name': 'Report'},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'URL'},
        ),
        migrations.AlterModelOptions(
            name='urllastmodified',
            options={'verbose_name': 'Last modified URL'},
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_last_modified_check',
            field=models.BooleanField(default=True, verbose_name='Tjek dato for sidste ændring'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='regex_rules',
            field=models.ManyToManyField(blank=True, related_name='scans', to='os2webscanner.RegexRule', verbose_name='Regex-regler'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='regex_rules',
            field=models.ManyToManyField(blank=True, related_name='scanners', to='os2webscanner.RegexRule', verbose_name='Regex-regler'),
        ),
    ]
