# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0064_adjust_labels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='urllastmodified',
            unique_together=set([('url', 'scanner')]),
        ),
    ]
