# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 16:35
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionqueueitem',
            name='process_start_time',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='Proces starttidspunkt', when=set(['PROCESSING'])),
        ),
        migrations.AlterField(
            model_name='conversionqueueitem',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='NEW', max_length=10, no_check_for_status=True, verbose_name='Status'),
        ),
    ]
