# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0002_scanner_statusfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangescan',
            name='scan_ptr',
        ),
        migrations.RemoveField(
            model_name='filescan',
            name='scan_ptr',
        ),
        migrations.DeleteModel(
            name='ExchangeScan',
        ),
        migrations.DeleteModel(
            name='FileScan',
        ),
    ]
