# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-01 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0003_related_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['-creation_time'], 'verbose_name': 'Report'},
        ),
    ]
