# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 13:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0003_remove_file_and_exchange_scans'),
    ]

    operations = [
        migrations.AddField(
            model_name='webversion',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
