# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("os2datascanner", "0003_remove_file_and_exchange_scans")]

    operations = [
        migrations.RemoveField(model_name="match", name="scan"),
        migrations.AlterField(
            model_name="webversion",
            name="scan",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="webversion_versions",
                to="os2datascanner.Scan",
                verbose_name="Scan",
            ),
        ),
    ]
