# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0004_infer_match_scanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrerurl',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrerurl_versions', to='os2datascanner.Scan', verbose_name='Scan'),
        ),
    ]
