# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-01 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0004_scan_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webversion',
            name='mime_type',
        ),
        migrations.AddField(
            model_name='version',
            name='mime_type',
            field=models.CharField(max_length=256, null=True, verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='conversionqueueitem',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner.Version', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='match',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='os2datascanner.Version', verbose_name='URL'),
        ),
    ]
