# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-01 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0005_version_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='os2datascanner.Location', verbose_name='Location'),
        ),
    ]
