# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 12:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0006_cascade_deleting_scanners'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
