# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0007_version_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='relevant_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='relevant_unsupported_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='supported_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typestatistics',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
