# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0008_auto_20180426_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionQueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=4096, verbose_name='Fil')),
                ('type', models.CharField(max_length=256, verbose_name='Type')),
                ('page_no', models.IntegerField(null=True, verbose_name='Side')),
                ('status', models.CharField(choices=[('NEW', 'Ny'), ('PROCESSING', 'I gang'), ('FAILED', 'Fejlet')], default='NEW', max_length=10, verbose_name='Status')),
                ('process_id', models.IntegerField(blank=True, null=True, verbose_name='Proces id')),
                ('process_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Proces starttidspunkt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_data', models.CharField(max_length=1024, verbose_name='Data match')),
                ('matched_rule', models.CharField(max_length=256, verbose_name='Regel match')),
                ('sensitivity', models.IntegerField(choices=[(0, 'Grøn'), (1, 'Gul'), (2, 'Rød')], default=2, verbose_name='Følsomhed')),
                ('match_context', models.CharField(max_length=1152, verbose_name='Kontekst')),
                ('page_no', models.IntegerField(null=True, verbose_name='Side')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Starttidspunkt')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Sluttidspunkt')),
                ('is_visible', models.BooleanField(default=True)),
                ('whitelisted_names', models.TextField(blank=True, default='', max_length=4096, verbose_name='Godkendte navne')),
                ('blacklisted_names', models.TextField(blank=True, default='', max_length=4096, verbose_name='Sortlistede navne')),
                ('whitelisted_addresses', models.TextField(blank=True, default='', max_length=4096, verbose_name='Godkendte adresser')),
                ('blacklisted_addresses', models.TextField(blank=True, default='', max_length=4096, verbose_name='Sortlistede adresser')),
                ('whitelisted_cprs', models.TextField(blank=True, default='', max_length=4096, verbose_name='Godkendte CPR-numre')),
                ('do_cpr_scan', models.BooleanField(default=True, verbose_name='CPR')),
                ('do_name_scan', models.BooleanField(default=False, verbose_name='Navn')),
                ('do_address_scan', models.BooleanField(default=False, verbose_name='Adresse')),
                ('do_ocr', models.BooleanField(default=False, verbose_name='Scan billeder')),
                ('do_cpr_modulus11', models.BooleanField(default=True, verbose_name='Tjek modulus-11')),
                ('do_cpr_ignore_irrelevant', models.BooleanField(default=True, verbose_name='Ignorer ugyldige fødselsdatoer')),
                ('do_last_modified_check', models.BooleanField(default=True, verbose_name='Tjek sidst ændret dato')),
                ('columns', models.CommaSeparatedIntegerField(blank=True, max_length=128, null=True)),
                ('output_spreadsheet_file', models.BooleanField(default=False)),
                ('do_cpr_replace', models.BooleanField(default=False)),
                ('cpr_replace_text', models.CharField(blank=True, max_length=2048, null=True)),
                ('do_name_replace', models.BooleanField(default=False)),
                ('name_replace_text', models.CharField(blank=True, max_length=2048, null=True)),
                ('do_address_replace', models.BooleanField(default=False)),
                ('address_replace_text', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Ny'), ('STARTED', 'I gang'), ('DONE', 'OK'), ('FAILED', 'Fejlet')], default='NEW', max_length=10)),
                ('pause_non_ocr_conversions', models.BooleanField(default=False, verbose_name='Pause non-OCR conversions')),
                ('reason', models.CharField(blank=True, default='', max_length=1024, verbose_name='Årsag')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='Pid')),
                ('recipients', models.ManyToManyField(blank=True, to='os2webscanner.UserProfile')),
                ('regex_rules', models.ManyToManyField(blank=True, to='os2webscanner.RegexRule', verbose_name='Regex regler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Navn')),
                ('schedule', recurrence.fields.RecurrenceField(max_length=1024, verbose_name='Planlagt afvikling')),
                ('do_cpr_scan', models.BooleanField(default=True, verbose_name='CPR')),
                ('do_name_scan', models.BooleanField(default=False, verbose_name='Navn')),
                ('do_address_scan', models.BooleanField(default=False, verbose_name='Adresse')),
                ('do_ocr', models.BooleanField(default=False, verbose_name='Scan billeder')),
                ('do_last_modified_check', models.BooleanField(default=True, verbose_name='Tjek sidst ændret dato')),
                ('do_cpr_modulus11', models.BooleanField(default=True, verbose_name='Tjek modulus-11')),
                ('do_cpr_ignore_irrelevant', models.BooleanField(default=True, verbose_name='Ignorer ugyldige fødselsdatoer')),
                ('columns', models.CommaSeparatedIntegerField(blank=True, max_length=128, null=True)),
                ('output_spreadsheet_file', models.BooleanField(default=False)),
                ('do_cpr_replace', models.BooleanField(default=False)),
                ('cpr_replace_text', models.CharField(blank=True, max_length=2048, null=True)),
                ('do_name_replace', models.BooleanField(default=False)),
                ('name_replace_text', models.CharField(blank=True, max_length=2048, null=True)),
                ('do_address_replace', models.BooleanField(default=False)),
                ('address_replace_text', models.CharField(blank=True, max_length=2048, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('encoded_process_urls', models.CharField(blank=True, max_length=262144, null=True)),
                ('do_run_synchronously', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Group', verbose_name='Gruppe')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Organization', verbose_name='Organisation')),
                ('recipients', models.ManyToManyField(blank=True, to='os2webscanner.UserProfile', verbose_name='Modtagere')),
                ('regex_rules', models.ManyToManyField(blank=True, to='os2webscanner.RegexRule', verbose_name='Regex regler')),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048, verbose_name='Url')),
                ('mime_type', models.CharField(max_length=256, verbose_name='Mime-type')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Status code')),
                ('status_message', models.CharField(blank=True, max_length=256, null=True, verbose_name='Status Message')),
                ('referrers', models.ManyToManyField(related_name='os2webscanner_url_linked_urls', to='os2webscanner.ReferrerUrl', verbose_name='Referrers')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='os2webscanner.Scan', verbose_name='Scan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fileconversionqueueitem',
            name='url',
        ),
        migrations.RemoveField(
            model_name='filematch',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='filematch',
            name='url',
        ),
        migrations.RemoveField(
            model_name='filescan',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='filescan',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='filescan',
            name='regex_rules',
        ),
        migrations.RemoveField(
            model_name='filescan',
            name='scanner',
        ),
        migrations.RemoveField(
            model_name='fileurl',
            name='referrers',
        ),
        migrations.RemoveField(
            model_name='fileurl',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='webconversionqueueitem',
            name='url',
        ),
        migrations.RemoveField(
            model_name='webmatch',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='webmatch',
            name='url',
        ),
        migrations.RemoveField(
            model_name='weburl',
            name='referrers',
        ),
        migrations.RemoveField(
            model_name='weburl',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='address_replace_text',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='cpr_replace_text',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='do_address_replace',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='do_address_scan',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='do_cpr_ignore_irrelevant',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='do_cpr_modulus11',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='do_cpr_replace',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='do_cpr_scan',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='do_last_modified_check',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='do_name_replace',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='do_name_scan',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='do_ocr',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='do_run_synchronously',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='encoded_process_urls',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='group',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='is_running',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='name_replace_text',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='output_spreadsheet_file',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='regex_rules',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='address_replace_text',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='blacklisted_addresses',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='blacklisted_names',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='cpr_replace_text',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='do_address_replace',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='do_address_scan',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='do_cpr_ignore_irrelevant',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='do_cpr_modulus11',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='do_cpr_replace',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='do_cpr_scan',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='do_last_modified_check',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='do_name_replace',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='do_name_scan',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='do_ocr',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='name_replace_text',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='output_spreadsheet_file',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='pause_non_ocr_conversions',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='regex_rules',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='whitelisted_addresses',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='whitelisted_cprs',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='whitelisted_names',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='address_replace_text',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='cpr_replace_text',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_address_replace',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_address_scan',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_cpr_ignore_irrelevant',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_cpr_modulus11',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_cpr_replace',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_cpr_scan',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_last_modified_check',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_name_replace',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_name_scan',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_ocr',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_run_synchronously',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='encoded_process_urls',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='group',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='is_running',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='name_replace_text',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='output_spreadsheet_file',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='regex_rules',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='FileConversionQueueItem',
        ),
        migrations.DeleteModel(
            name='FileMatch',
        ),
        migrations.DeleteModel(
            name='FileScan',
        ),
        migrations.DeleteModel(
            name='FileUrl',
        ),
        migrations.DeleteModel(
            name='WebConversionQueueItem',
        ),
        migrations.DeleteModel(
            name='WebMatch',
        ),
        migrations.DeleteModel(
            name='WebUrl',
        ),
        migrations.AddField(
            model_name='filescanner',
            name='scanner_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2webscanner.Scanner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webscan',
            name='scan_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2webscanner.Scan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webscanner',
            name='scanner_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2webscanner.Scanner'),
            preserve_default=False,
        ),
    ]
