# Generated by Django 1.11.9 on 2018-04-26 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0009_auto_20180426_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionqueueitem',
            name='url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Url', verbose_name='Url'),
            preserve_default=False,
        ),
    ]
