# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0009_concrete_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='regex_rules',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='regex_rules',
        ),
        migrations.AddField(
            model_name='scan',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='scans', to='os2datascanner.Rule', verbose_name='Regler'),
        ),
        migrations.AddField(
            model_name='scanner',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='scanners', to='os2datascanner.Rule', verbose_name='Regler'),
        ),
    ]
