# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0010_scan_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regexpattern',
            options={'ordering': ('pk',)},
        ),
    ]
