# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0011_regexpattern_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regexrule',
            name='cpr_enabled',
        ),
        migrations.RemoveField(
            model_name='regexrule',
            name='do_modulus11',
        ),
        migrations.RemoveField(
            model_name='regexrule',
            name='ignore_irrelevant',
        ),
    ]
