# Generated by Django 1.11.9 on 2018-05-01 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0011_filedomain_mountname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filescanner',
            table=None,
        ),
        migrations.AlterModelTable(
            name='webscanner',
            table=None,
        ),
    ]
