# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-01 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0012_auto_20180501_1004'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scanner',
            table='os2webscanner_scanner',
        ),
    ]
