# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0013_addressrule_namerule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='do_address_scan',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='do_name_scan',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='do_address_scan',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='do_name_scan',
        ),
    ]
