# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0014_remove_special_scan_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address_blacklist',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address_whitelist',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='cpr_whitelist',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_blacklist',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_whitelist',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='blacklisted_addresses',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='blacklisted_names',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='whitelisted_addresses',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='whitelisted_cprs',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='whitelisted_names',
        ),
        migrations.AddField(
            model_name='addressrule',
            name='blacklist',
            field=models.TextField(blank=True, default='', verbose_name='Sortlistede adresser'),
        ),
        migrations.AddField(
            model_name='addressrule',
            name='whitelist',
            field=models.TextField(blank=True, default='', verbose_name='Godkendte adresser'),
        ),
        migrations.AddField(
            model_name='cprrule',
            name='whitelist',
            field=models.TextField(blank=True, default='', verbose_name='Godkendte CPR-numre'),
        ),
        migrations.AddField(
            model_name='namerule',
            name='blacklist',
            field=models.TextField(blank=True, default='', verbose_name='Sortlistede navne'),
        ),
        migrations.AddField(
            model_name='namerule',
            name='whitelist',
            field=models.TextField(blank=True, default='', verbose_name='Godkendte navne'),
        ),
    ]
