# Generated by Django 1.11.9 on 2018-05-01 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0014_auto_20180501_1010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filescanner',
            table='os2webscanner_filescanner',
        ),
        migrations.AlterModelTable(
            name='webscan',
            table='os2webscanner_webscan',
        ),
        migrations.AlterModelTable(
            name='webscanner',
            table='os2webscanner_webscanner',
        ),
    ]
