# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0015_remove_organization_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='relevant_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='relevant_unsupported_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='supported_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typestatistics',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
