# Generated by Django 2.2.4 on 2019-09-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0017_initial_aliases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsidalias',
            options={'verbose_name': 'ADSID alias', 'verbose_name_plural': 'ADSID aliases'},
        ),
    ]
