# Generated by Django 2.2.4 on 2020-01-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0018_exchangescanner_service_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangescanner',
            name='dir_to_scan',
        ),
        migrations.RemoveField(
            model_name='exchangescanner',
            name='is_exporting',
        ),
        migrations.RemoveField(
            model_name='exchangescanner',
            name='is_ready_to_scan',
        ),
        migrations.RemoveField(
            model_name='filescanner',
            name='mountpath',
        ),
    ]
