# Generated by Django 1.11.9 on 2018-05-01 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0021_auto_20180501_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='os2webscanner.Scan', verbose_name='Scan'),
        ),
        migrations.AlterField(
            model_name='match',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Url', verbose_name='Url'),
        ),
    ]
