# Generated by Django 1.11.9 on 2018-05-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0027_auto_20180504_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllastmodified',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Scanner', verbose_name='WebScanner'),
        ),
    ]
