# Generated by Django 1.11.9 on 2018-05-28 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0028_auto_20180522_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=2024, verbose_name='Bruger domæne'),
        ),
    ]
