# Generated by Django 1.11.9 on 2018-06-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0029_authentication_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegexPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_string', models.CharField(max_length=1024, verbose_name='Udtryk')),
            ],
        ),
        migrations.RemoveField(
            model_name='regexrule',
            name='match_string',
        ),
        migrations.AddField(
            model_name='regexpattern',
            name='regex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='os2webscanner.RegexRule', verbose_name='Regex'),
        ),
    ]
