# Generated by Django 1.11.9 on 2018-06-12 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0029_authentication_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='files_added_to_the_queue_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='successfully_processed_files_count',
            field=models.IntegerField(default=0),
        ),
    ]
