# Generated by Django 1.11.9 on 2018-06-13 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0030_auto_20180612_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='files_added_to_the_queue_count',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='successfully_processed_files_count',
        ),
    ]
