# Generated by Django 1.11.9 on 2018-07-11 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0037_merge_20180620_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='do_cpr_ignore_irrelevant',
            field=models.BooleanField(default=True, verbose_name='Ignorer ugyldige fødselsdatoer'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_cpr_modulus11',
            field=models.BooleanField(default=True, verbose_name='Tjek modulus-11'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_last_modified_check',
            field=models.BooleanField(default=True, verbose_name='Tjek sidst ændret dato'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_cpr_ignore_irrelevant',
            field=models.BooleanField(default=True, verbose_name='Ignorer ugyldige fødselsdatoer'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_cpr_modulus11',
            field=models.BooleanField(default=True, verbose_name='Tjek modulus-11'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_last_modified_check',
            field=models.BooleanField(default=True, verbose_name='Tjek sidst ændret dato'),
        ),
    ]
