# Generated by Django 1.11.9 on 2018-08-13 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0037_merge_20180811_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexrule',
            name='cpr_enabled',
            field=models.BooleanField(default=False, verbose_name='Scan CPR'),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='ignore_irrelevant',
            field=models.BooleanField(default=False, verbose_name='Ignorer ugyldige fødselsdatoer'),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='mod11_enabled',
            field=models.BooleanField(default=False, verbose_name='Tjek modulus-11'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_cpr_ignore_irrelevant',
            field=models.BooleanField(default=True, verbose_name='Ignorer ugyldige fødselsdatoer'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_cpr_modulus11',
            field=models.BooleanField(default=True, verbose_name='Tjek modulus-11'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_last_modified_check',
            field=models.BooleanField(default=True, verbose_name='Tjek sidst ændret dato'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_cpr_ignore_irrelevant',
            field=models.BooleanField(default=True, verbose_name='Ignorer ugyldige fødselsdatoer'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_cpr_modulus11',
            field=models.BooleanField(default=True, verbose_name='Tjek modulus-11'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_last_modified_check',
            field=models.BooleanField(default=True, verbose_name='Tjek sidst ændret dato'),
        ),
    ]
