# Generated by Django 1.11.14 on 2018-08-17 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0040_auto_20180814_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regexrule',
            old_name='mod11_enabled',
            new_name='do_modulus11',
        ),
    ]
