# Generated by Django 1.11.9 on 2018-08-02 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0044_exchangescan_mark_scan_as_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangescan',
            name='last_scannings_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sidste scanningstidspunkt'),
        ),
        migrations.AddField(
            model_name='exchangescanner',
            name='last_scannings_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sidste scanningstidspunkt'),
        ),
    ]
