# Generated by Django 1.11.20 on 2019-03-07 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0056_auto_20190219_1058'),
        ('os2webscanner', '0054_filedomain_alias'),
    ]

    operations = [
    ]
