# Generated by Django 1.11.20 on 2019-04-12 17:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0061_infer_scanner_is_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='encoded_process_urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='scanner',
            old_name='encoded_process_urls',
            new_name='process_urls',
        ),
    ]
