# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0066_statistics_nonnull_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='match',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Url', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='referrerurl',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_last_modified_check',
            field=models.BooleanField(default=True, help_text='Scan udelukkende filer der rapporteres som nyere end sidste scanning', verbose_name='Tjek dato for sidste ændring'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='urllastmodified',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='webdomain',
            name='sitemap_url',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Sitemap URL'),
        ),
        migrations.AlterField(
            model_name='webscan',
            name='do_collect_cookies',
            field=models.BooleanField(default=False, verbose_name='Opsaml cookies'),
        ),
        migrations.AlterField(
            model_name='webscan',
            name='do_external_link_check',
            field=models.BooleanField(default=False, verbose_name='Tjek eksterne links'),
        ),
        migrations.AlterField(
            model_name='webscan',
            name='do_last_modified_check_head_request',
            field=models.BooleanField(default=True, help_text='Tjek datoer ved hjælp af en særskilt forespørgsel', verbose_name='Brug HTTP HEAD-forespørgsler'),
        ),
    ]
