# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("os2webscanner", "0067_adjust_verbose_names")]

    operations = [
        migrations.RenameModel("Url", "Version"),
        migrations.AlterModelOptions(
            name='version',
            options={},
        ),
        migrations.AlterField(
            model_name="version",
            name="referrers",
            field=models.ManyToManyField(
                related_name="os2webscanner_version_linked_urls",
                to="os2webscanner.ReferrerUrl",
                verbose_name="Referrers",
            ),
        ),
        migrations.AlterField(
            model_name='conversionqueueitem',
            name='url',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='os2webscanner.Version', verbose_name='URL'),
        ),
    ]
