# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0068_rename_url_to_version'),
    ]

    operations = [
        migrations.RenameModel('Version', 'WebVersion'),
        migrations.AlterField(
            model_name='webversion',
            name='referrers',
            field=models.ManyToManyField(related_name='os2webscanner_webversion_linked_urls', to='os2webscanner.ReferrerUrl', verbose_name='Referrers'),
        ),
    ]
