# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0069_split_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Navn'),
        ),
    ]
