# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 14:04


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0003_organization_do_notify_all_scans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionqueueitem',
            name='file',
            field=models.CharField(max_length=4096, verbose_name='Fil'),
        ),
        migrations.AlterField(
            model_name='conversionqueueitem',
            name='page_no',
            field=models.IntegerField(null=True, verbose_name='Side'),
        ),
        migrations.AlterField(
            model_name='conversionqueueitem',
            name='process_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Proces id'),
        ),
        migrations.AlterField(
            model_name='conversionqueueitem',
            name='process_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proces starttidspunkt'),
        ),
        migrations.AlterField(
            model_name='conversionqueueitem',
            name='status',
            field=models.CharField(choices=[('NEW', 'Ny'), ('PROCESSING', 'I gang'), ('FAILED', 'Fejlet')], default='NEW', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='conversionqueueitem',
            name='type',
            field=models.CharField(max_length=256, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='conversionqueueitem',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Url', verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='download_sitemap',
            field=models.BooleanField(default=True, verbose_name='Hent Sitemap fra serveren'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='exclusion_rules',
            field=models.TextField(blank=True, default='', verbose_name='Ekskluderingsregler'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='os2webscanner.Group', verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='sitemap',
            field=models.FileField(blank=True, upload_to='sitemaps', verbose_name='Sitemap Fil'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='sitemap_url',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Sitemap Url'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='validation_method',
            field=models.IntegerField(choices=[(0, 'robots.txt'), (1, 'webscan.html'), (2, 'Meta-felt')], default=0, verbose_name='Valideringsmetode'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='validation_status',
            field=models.IntegerField(choices=[(0, 'Ugyldig'), (1, 'Gyldig')], default=0, verbose_name='Valideringsstatus'),
        ),
        migrations.AlterField(
            model_name='group',
            name='contact_email',
            field=models.CharField(max_length=256, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='group',
            name='contact_phone',
            field=models.CharField(max_length=256, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user_profiles',
            field=models.ManyToManyField(blank=True, related_name='groups', to='os2webscanner.UserProfile', verbose_name='Brugere'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_context',
            field=models.CharField(max_length=1152, verbose_name='Kontekst'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matched_data',
            field=models.CharField(max_length=1024, verbose_name='Data match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matched_rule',
            field=models.CharField(max_length=256, verbose_name='Regel match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='page_no',
            field=models.IntegerField(null=True, verbose_name='Side'),
        ),
        migrations.AlterField(
            model_name='match',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='os2webscanner.Scan', verbose_name='Scan'),
        ),
        migrations.AlterField(
            model_name='match',
            name='sensitivity',
            field=models.IntegerField(choices=[(0, 'Grøn'), (1, 'Gul'), (2, 'Rød')], default=2, verbose_name='Følsomhed'),
        ),
        migrations.AlterField(
            model_name='match',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Url', verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='md5sum',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_blacklist',
            field=models.TextField(blank=True, default='', verbose_name='Sortlistede adresser'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_whitelist',
            field=models.TextField(blank=True, default='', verbose_name='Godkendte adresser'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_email',
            field=models.CharField(max_length=256, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(max_length=256, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cpr_whitelist',
            field=models.TextField(blank=True, default='', verbose_name='Godkendte CPR-numre'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_blacklist',
            field=models.TextField(blank=True, default='', verbose_name='Sortlistede navne'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_whitelist',
            field=models.TextField(blank=True, default='', verbose_name='Godkendte navne'),
        ),
        migrations.AlterField(
            model_name='referrerurl',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Scan', verbose_name='Scan'),
        ),
        migrations.AlterField(
            model_name='referrerurl',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='regexrule',
            name='description',
            field=models.TextField(verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='regexrule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Group', verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='regexrule',
            name='match_string',
            field=models.CharField(max_length=1024, verbose_name='Udtryk'),
        ),
        migrations.AlterField(
            model_name='regexrule',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='regexrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='regexrule',
            name='sensitivity',
            field=models.IntegerField(choices=[(0, 'Grøn'), (1, 'Gul'), (2, 'Rød')], default=2, verbose_name='Følsomhed'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='blacklisted_addresses',
            field=models.TextField(blank=True, default='', max_length=4096, verbose_name='Sortlistede adresser'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='blacklisted_names',
            field=models.TextField(blank=True, default='', max_length=4096, verbose_name='Sortlistede navne'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_address_scan',
            field=models.BooleanField(default=False, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_collect_cookies',
            field=models.BooleanField(default=False, verbose_name='Saml cookies'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_cpr_ignore_irrelevant',
            field=models.BooleanField(default=True, verbose_name='Ignorer ugyldige fødselsdatoer'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_cpr_modulus11',
            field=models.BooleanField(default=True, verbose_name='Tjek modulus-11'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_cpr_scan',
            field=models.BooleanField(default=True, verbose_name='CPR'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_external_link_check',
            field=models.BooleanField(default=False, verbose_name='Eksterne links'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_last_modified_check',
            field=models.BooleanField(default=True, verbose_name='Tjek Last-Modified'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_last_modified_check_head_request',
            field=models.BooleanField(default=True, verbose_name='Brug HEAD request'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_name_scan',
            field=models.BooleanField(default=False, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='do_ocr',
            field=models.BooleanField(default=False, verbose_name='Scan billeder'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='domains',
            field=models.ManyToManyField(to='os2webscanner.Domain', verbose_name='Domæner'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sluttidspunkt'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='pause_non_ocr_conversions',
            field=models.BooleanField(default=False, verbose_name='Pause non-OCR conversions'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pid'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Årsag'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='regex_rules',
            field=models.ManyToManyField(blank=True, to='os2webscanner.RegexRule', verbose_name='Regex regler'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='os2webscanner.Scanner', verbose_name='Scanner'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Starttidspunkt'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('NEW', 'Ny'), ('STARTED', 'I gang'), ('DONE', 'OK'), ('FAILED', 'Fejlet')], default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='scan',
            name='whitelisted_addresses',
            field=models.TextField(blank=True, default='', max_length=4096, verbose_name='Godkendte adresser'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='whitelisted_cprs',
            field=models.TextField(blank=True, default='', max_length=4096, verbose_name='Godkendte CPR-numre'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='whitelisted_names',
            field=models.TextField(blank=True, default='', max_length=4096, verbose_name='Godkendte navne'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_address_scan',
            field=models.BooleanField(default=False, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_collect_cookies',
            field=models.BooleanField(default=False, verbose_name='Saml cookies'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_cpr_ignore_irrelevant',
            field=models.BooleanField(default=True, verbose_name='Ignorer ugyldige fødselsdatoer'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_cpr_modulus11',
            field=models.BooleanField(default=True, verbose_name='Tjek modulus-11'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_cpr_scan',
            field=models.BooleanField(default=True, verbose_name='CPR'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_external_link_check',
            field=models.BooleanField(default=False, verbose_name='Eksterne links'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_last_modified_check',
            field=models.BooleanField(default=True, verbose_name='Tjek Last-Modified'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_last_modified_check_head_request',
            field=models.BooleanField(default=True, verbose_name='Brug HEAD request'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_name_scan',
            field=models.BooleanField(default=False, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_ocr',
            field=models.BooleanField(default=False, verbose_name='Scan billeder'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='domains',
            field=models.ManyToManyField(related_name='scanners', to='os2webscanner.Domain', verbose_name='Domæner'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Group', verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='os2webscanner.UserProfile', verbose_name='Modtagere'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='regex_rules',
            field=models.ManyToManyField(blank=True, to='os2webscanner.RegexRule', verbose_name='Regex regler'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='schedule',
            field=recurrence.fields.RecurrenceField(max_length=1024, verbose_name='Planlagt afvikling'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='do_email_recipients',
            field=models.BooleanField(default=False, verbose_name='Udsend mails'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Group', verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sidste kørsel'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='os2webscanner.UserProfile', verbose_name='Modtagere'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='scanners',
            field=models.ManyToManyField(blank=True, to='os2webscanner.Scanner', verbose_name='Scannere'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='schedule',
            field=recurrence.fields.RecurrenceField(max_length=1024, verbose_name='Planlagt afvikling'),
        ),
        migrations.AlterField(
            model_name='url',
            name='mime_type',
            field=models.CharField(max_length=256, verbose_name='Mime-type'),
        ),
        migrations.AlterField(
            model_name='url',
            name='referrers',
            field=models.ManyToManyField(related_name='linked_urls', to='os2webscanner.ReferrerUrl', verbose_name='Referrers'),
        ),
        migrations.AlterField(
            model_name='url',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='os2webscanner.Scan', verbose_name='Scan'),
        ),
        migrations.AlterField(
            model_name='url',
            name='status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Status code'),
        ),
        migrations.AlterField(
            model_name='url',
            name='status_message',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Status Message'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='urllastmodified',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last-modified'),
        ),
        migrations.AlterField(
            model_name='urllastmodified',
            name='links',
            field=models.ManyToManyField(to='os2webscanner.UrlLastModified', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='urllastmodified',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Scanner', verbose_name='Scanner'),
        ),
        migrations.AlterField(
            model_name='urllastmodified',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Bruger'),
        ),
    ]
