# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0010_conversionqueueitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedomain',
            name='mountname',
            field=models.CharField(max_length=2048, null=True, verbose_name='Folder navn'),
        ),
    ]
