# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-01 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0020_filescan'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='os2webscanner.Scan', verbose_name='Scan'),
        ),
        migrations.AddField(
            model_name='match',
            name='url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='os2webscanner.Url', verbose_name='Url'),
        ),
    ]
