# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-02 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0024_auto_20180502_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filescan',
            name='scanner',
        ),
        migrations.RemoveField(
            model_name='webscan',
            name='scanner',
        ),
        migrations.AddField(
            model_name='scan',
            name='scanner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='webscans', to='os2webscanner.Scanner', verbose_name='webscanner', null=True),
            preserve_default=False,
        ),
    ]
