ALTER TABLE os2webscanner_scan
ADD COLUMN "output_spreadsheet_file" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN "do_cpr_replace" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN "cpr_replace_text" VARCHAR(2048),
ADD COLUMN "do_name_replace" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN "name_replace_text" VARCHAR(2048) DEFAULT FALSE,
ADD COLUMN "do_address_replace" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN "address_replace_text" VARCHAR(2048) DEFAULT FALSE;


ALTER TABLE os2webscanner_scanner
ADD COLUMN "output_spreadsheet_file" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN "do_cpr_replace" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN "cpr_replace_text" VARCHAR(2048),
ADD COLUMN "do_name_replace" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN "name_replace_text" VARCHAR(2048) DEFAULT FALSE,
ADD COLUMN "do_address_replace" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN "address_replace_text" VARCHAR(2048) DEFAULT FALSE;

