# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-24 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReport',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('path', models.CharField(max_length=2000)),
            ],
        ),
    ]
