# Generated by Django 2.2.4 on 2019-11-05 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import os2datascanner.projects.report.reportapp.models.aliases.adsidalias_model


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('os2datascanner_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to=settings.AUTH_USER_MODEL, verbose_name='Bruger')),
            ],
        ),
        migrations.CreateModel(
            name='ADSIDAlias',
            fields=[
                ('alias_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner_report.Alias')),
                ('sid', models.CharField(max_length=192, validators=[os2datascanner.projects.report.reportapp.models.aliases.adsidalias_model.validate_sid], verbose_name='SID')),
            ],
            options={
                'verbose_name': 'ADSID alias',
                'verbose_name_plural': 'ADSID aliases',
            },
            bases=('os2datascanner_report.alias',),
        ),
        migrations.CreateModel(
            name='EmailAlias',
            fields=[
                ('alias_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner_report.Alias')),
                ('address', models.EmailField(max_length=254, verbose_name='Mailadresse')),
            ],
            options={
                'verbose_name_plural': 'Email aliases',
            },
            bases=('os2datascanner_report.alias',),
        ),
    ]
