# Generated by Django 2.2.4 on 2020-01-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0003_documentreport_jsonbfield_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentreport',
            options={'verbose_name_plural': 'Document reports'},
        ),
    ]
